### ISSUE TITLE
Problem with npm 3

### ISSUE THREAD

**Issue by bogdan-r** [lykmapipo/sails-hook-validation#25]
Hello.

When I try run sails app, I get next error:

```javascript
error: Error: Cannot find module 'sails/node_modules/waterline/lib/waterline/query/deferred'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/user/projects/happsy/happsyphoto/node_modules/sails-hook-validation/lib/create.js:5:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/user/projects/happsy/happsyphoto/node_modules/sails-hook-validation/index.js:10:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
In npm 3 modules have flat structure and waterline module installed outside sails folder. I think you should include waterline module in your package.json like dependence.
In advance, thanks.
P.S. sorry for my bad english.

**Comment by lykmapipo** [comment]
@bogdan-r 

I will appreciate a pull request to fix this.

Thanks

**Comment by lykmapipo** [comment]
@bogdan-r 

It will appreciate reopen of this issue with a pull request.

**Comment by ablipan** [comment]
@lykmapipo This issue is not fix yet. :cry:

**Comment by lykmapipo** [comment]
@ablipan 

I will appreciate pull request to fix this issue. Else may you please provide me with the `node and npm version` so that i can work with it. I will appreciate if its stable `npm` version

**Comment by ablipan** [comment]
npm : no3.5.0
node: v4.2.1
Have this issue with the `root` user.
But do not know why, after switching to the normal user, the issue is disappeared.

**Comment by aohx075** [comment]
+1

npm: v3.3.12
node: v4.2.2

**Comment by lykmapipo** [comment]
@aohx075 

Will be fixed on next version.

**Comment by semy** [comment]
status? can't us it :-(

**Comment by lykmapipo** [comment]
Hello,

I managed to merge pull requests but all specs failed. Am now working to fix them.
Soon it will be out.

Sorry.
